### ISSUE TITLE
Display a more meaningful error instead of a stack trace when submissionSet patientId is missing 

### ISSUE THREAD

**Issue by skbhaskarla** [usnistgov/iheos-toolkit2#564] opened 2022-09-13 19:26 UTC
<rs:RegistryError codeContext="SOAP Fault: No Message&#xA;Exception NullPointerException&#xA;	at gov.nist.toolkit.configDatatypes.client.PidBuilder.createPid(PidBuilder.java:15)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.reg.RegRSim.run(RegRSim.java:76)&#xA;	at gov.nist.toolkit.valsupport.engine.MessageValidatorEngine.run(MessageValidatorEngine.java:165)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.reg.RegistryActorSimulator.run(RegistryActorSimulator.java:195)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.rg.RGADActorSimulator.run(RGADActorSimulator.java:39)&#xA;	at gov.nist.toolkit.fhir.simulators.servlet.SimServlet.doPost(SimServlet.java:700)&#xA;	at gov.nist.toolkit.fhir.simulators.servlet.SimServletFilter.doFilter(SimServletFilter.java:39)&#xA;&#xA;Exception XdsInternalException&#xA;	gov.nist.toolkit.xdsexception.client.XdsInternalException: SOAP Fault: No Message&#xA;	at gov.nist.toolkit.configDatatypes.client.PidBuilder.createPid(PidBuilder.java:15)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.reg.RegRSim.run(RegRSim.java:76)&#xA;	at gov.nist.toolkit.valsupport.engine.MessageValidatorEngine.run(MessageValidatorEngine.java:165)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.reg.RegistryActorSimulator.run(RegistryActorSimulator.java:195)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.rg.RGADActorSimulator.run(RGADActorSimulator.java:39)&#xA;	at gov.nist.toolkit.fhir.simulators.servlet.SimServlet.doPost(SimServlet.java:700)&#xA;	at gov.nist.toolkit.fhir.simulators.servlet.SimServletFilter.doFilter(SimServletFilter.java:39)&#xA;	at gov.nist.toolkit.soap.axis2.Soap.soapCallWithWSSEC(Soap.java:602)&#xA;	at gov.nist.toolkit.soap.axis2.Soap.soapCall(Soap.java:712)&#xA;	at gov.nist.toolkit.soap.axis2.Soap.soapCall(Soap.java:939)&#xA;	at gov.nist.toolkit.soap.axis2.Soap.soapCall(Soap.java:913)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.rep.RepPnRSim.run(RepPnRSim.java:225)&#xA;	at gov.nist.toolkit.valsupport.engine.MessageValidatorEngine.run(MessageValidatorEngine.java:165)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.rep.RepositoryActorSimulator.run(RepositoryActorSimulator.java:135)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.rg.RGADActorSimulator.run(RGADActorSimulator.java:37)&#xA;	at gov.nist.toolkit.fhir.simulators.servlet.SimServlet.doPost(SimServlet.java:700)&#xA;	at gov.nist.toolkit.fhir.simulators.servlet.SimServletFilter.doFilter(SimServletFilter.java:39)&#xA;	at gov.nist.toolkit.configDatatypes.client.PidBuilder.createPid(PidBuilder.java:15)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.reg.RegRSim.run(RegRSim.java:76)&#xA;	at gov.nist.toolkit.valsupport.engine.MessageValidatorEngine.run(MessageValidatorEngine.java:165)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.reg.RegistryActorSimulator.run(RegistryActorSimulator.java:195)&#xA;	at gov.nist.toolkit.fhir.simulators.sim.rg.RGADActorSimulator.run(RGADActorSimulator.java:39)&#xA;	at gov.nist.toolkit.fhir.simulators.servlet.SimServlet.doPost(SimServlet.java:700)&#xA;	at gov.nist.toolkit.fhir.simulators.servlet.SimServletFilter.doFilter(SimServletFilter.java:39)&#xA;	at gov.nist.toolkit.soap.axis2.Soap.soapCallWithWSSEC(Soap.java:566)" errorCode="XDSRepositoryError" location="" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error" />

**Comment by andrewmccaffreynist** [comment] 2022-12-05 22:09
Unable to reproduce bug locally. See sample request and response attached. Closing for now.
[Broken PnR request.txt](https://github.com/usnistgov/iheos-toolkit2/files/10158253/Broken.PnR.request.txt)
[Broken PnR response.txt](https://github.com/usnistgov/iheos-toolkit2/files/10158254/Broken.PnR.response.txt)

**Closed** 2022-12-05 22:09 UTC
